package com.upload.resourceupload.dao;

import com.upload.resourceupload.entity.FileTitle;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface FileTitleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filetitle
     *
     * @mbg.generated Wed Nov 06 14:47:52 JST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filetitle
     *
     * @mbg.generated Wed Nov 06 14:47:52 JST 2019
     */
    int insert(FileTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filetitle
     *
     * @mbg.generated Wed Nov 06 14:47:52 JST 2019
     */
    int insertSelective(FileTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filetitle
     *
     * @mbg.generated Wed Nov 06 14:47:52 JST 2019
     */
    FileTitle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filetitle
     *
     * @mbg.generated Wed Nov 06 14:47:52 JST 2019
     */
    int updateByPrimaryKeySelective(FileTitle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table filetitle
     *
     * @mbg.generated Wed Nov 06 14:47:52 JST 2019
     */
    int updateByPrimaryKey(FileTitle record);
    List<FileTitle> selectAll();
}