package com.upload.resourceupload.dao;

import com.upload.resourceupload.entity.FileUpload;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface FileUploadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileupload
     *
     * @mbg.generated Wed Nov 06 22:47:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileupload
     *
     * @mbg.generated Wed Nov 06 22:47:59 CST 2019
     */
    int insert(FileUpload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileupload
     *
     * @mbg.generated Wed Nov 06 22:47:59 CST 2019
     */
    int insertSelective(FileUpload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileupload
     *
     * @mbg.generated Wed Nov 06 22:47:59 CST 2019
     */
    FileUpload selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileupload
     *
     * @mbg.generated Wed Nov 06 22:47:59 CST 2019
     */
    int updateByPrimaryKeySelective(FileUpload record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fileupload
     *
     * @mbg.generated Wed Nov 06 22:47:59 CST 2019
     */
    int updateByPrimaryKey(FileUpload record);
    List<FileUpload> getFileByTitleId(Integer tid);
    List<FileUpload> getAllUploadFile();
}