package com.upload.resourceupload.entity;

import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class FileUpload {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileupload.id
     *
     * @mbg.generated Wed Nov 06 22:47:59 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileupload.uuidname
     *
     * @mbg.generated Wed Nov 06 22:47:59 CST 2019
     */
    private String uuidname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileupload.filename
     *
     * @mbg.generated Wed Nov 06 22:47:59 CST 2019
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileupload.savepath
     *
     * @mbg.generated Wed Nov 06 22:47:59 CST 2019
     */
    private String savepath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileupload.uploadtime
     *
     * @mbg.generated Wed Nov 06 22:47:59 CST 2019
     */
    private LocalDateTime uploadtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileupload.size
     *
     * @mbg.generated Wed Nov 06 22:47:59 CST 2019
     */
    private Float size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileupload.url
     *
     * @mbg.generated Wed Nov 06 22:47:59 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileupload.description
     *
     * @mbg.generated Wed Nov 06 22:47:59 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileupload.username
     *
     * @mbg.generated Wed Nov 06 22:47:59 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fileupload.title_id
     *
     * @mbg.generated Wed Nov 06 22:47:59 CST 2019
     */
    private Integer titleId;
}