package com.upload.resourceupload.entity;

public class FileTitle {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filetitle.id
     *
     * @mbg.generated Wed Nov 06 14:47:52 JST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column filetitle.title_name
     *
     * @mbg.generated Wed Nov 06 14:47:52 JST 2019
     */
    private String titleName;

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitleName() {
		return titleName;
	}

	public void setTitleName(String titleName) {
		this.titleName = titleName;
	}

	@Override
	public String toString() {
		return "FileTitle [id=" + id + ", titleName=" + titleName + "]";
	}

}